export default {
  login: "nan",
  id: 74832,
  node_id: "MDQ6VXNlcjc0ODMy",
  avatar_url: "https://avatars.githubusercontent.com/u/74832?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/nan",
  html_url: "https://github.com/nan",
  followers_url: "https://api.github.com/users/nan/followers",
  following_url: "https://api.github.com/users/nan/following{/other_user}",
  gists_url: "https://api.github.com/users/nan/gists{/gist_id}",
  starred_url: "https://api.github.com/users/nan/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/nan/subscriptions",
  organizations_url: "https://api.github.com/users/nan/orgs",
  repos_url: "https://api.github.com/users/nan/repos",
  events_url: "https://api.github.com/users/nan/events{/privacy}",
  received_events_url: "https://api.github.com/users/nan/received_events",
  type: "User",
  site_admin: false,
  score: 1,
};
